#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CompraloTo;
    using CompraloTo.Res;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Email/_LayoutEmail.cshtml")]
    public partial class _Views_Email__LayoutEmail_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Email__LayoutEmail_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org" +
"/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html");

WriteLiteral(" xmlns=\"http://www.w3.org/1999/xhtml\"");

WriteLiteral(">\r\n<head>\r\n\t<meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=UTF-8\"");

WriteLiteral(" />\r\n\t<title>");

            
            #line 5 "..\..\Views\Email\_LayoutEmail.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n\t<meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(" />\r\n\r\n");

            
            #line 8 "..\..\Views\Email\_LayoutEmail.cshtml"
	
            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Email\_LayoutEmail.cshtml"
     if (IsSectionDefined("AddToHead"))
	{
		
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Email\_LayoutEmail.cshtml"
   Write(RenderSection("AddToHead", required: false));

            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Email\_LayoutEmail.cshtml"
                                                    
	}

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n</head>\r\n<body");

WriteLiteral(" style=\"font-family: Arial, Helvetica, sans-serif;font-size: 14px;\"");

WriteLiteral(">\r\n\r\n    <div");

WriteLiteral(" style=\"width:100%;max-width:600px;\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 18 "..\..\Views\Email\_LayoutEmail.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
