#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CompraloTo;
    using CompraloTo.Res;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Email/ActivationTemplate.cshtml")]
    public partial class _Views_Email_ActivationTemplate_cshtml : System.Web.Mvc.WebViewPage<CompraloTo.ViewModels.ActivationEmailViewModel>
    {
        public _Views_Email_ActivationTemplate_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Email\ActivationTemplate.cshtml"
  
    ViewBag.Title = "Index";
    Layout = "~/Views/Email/_LayoutEmail.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<div");

WriteLiteral(" style=\"text-align:justify;padding:5px;clear:both;margin-bottom:10px;\"");

WriteLiteral(">\r\n    <h3>\r\n        Bienvenido a CompraloTó\r\n    </h3>\r\n</div>\r\n\r\n\r\n<div");

WriteLiteral(" style=\"text-align:justify;padding:5px;clear:both;margin-bottom:10px;\"");

WriteLiteral(">\r\n    <h3>\r\n        Haga click en el siguiente enlace para activar su cuenta\r\n  " +
"  </h3>\r\n    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 460), Tuple.Create("\"", 571)
, Tuple.Create(Tuple.Create("", 467), Tuple.Create("http://localhost:5050/account/activate?email=", 467), true)
            
            #line 19 "..\..\Views\Email\ActivationTemplate.cshtml"
, Tuple.Create(Tuple.Create("", 512), Tuple.Create<System.Object, System.Int32>(Url.Encode(Model.email)
            
            #line default
            #line hidden
, 512), false)
, Tuple.Create(Tuple.Create("", 538), Tuple.Create("&token=", 538), true)
            
            #line 19 "..\..\Views\Email\ActivationTemplate.cshtml"
             , Tuple.Create(Tuple.Create("", 545), Tuple.Create<System.Object, System.Int32>(Url.Encode(Model.token)
            
            #line default
            #line hidden
, 545), false)
);

WriteLiteral(">Activar</a>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
