#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CompraloTo;
    using CompraloTo.Res;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ActivateResult.cshtml")]
    public partial class _Views_Account_ActivateResult_cshtml : System.Web.Mvc.WebViewPage<CompraloTo.ViewModels.ActivationEmailViewModel>
    {
        public _Views_Account_ActivateResult_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Account\ActivateResult.cshtml"
  
    ViewBag.Title = "Registro de nuevo usuario";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 6 "..\..\Views\Account\ActivateResult.cshtml"
 if (!string.IsNullOrEmpty(Model.successMessage))
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"alert alert-success\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 9 "..\..\Views\Account\ActivateResult.cshtml"
   Write(Model.successMessage);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 11 "..\..\Views\Account\ActivateResult.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"alert alert-danger\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 15 "..\..\Views\Account\ActivateResult.cshtml"
   Write(Model.errorMessage);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 17 "..\..\Views\Account\ActivateResult.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
