#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CompraloTo;
    using CompraloTo.Res;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Customers/CustomerListView.cshtml")]
    public partial class _Views_Customers_CustomerListView_cshtml : System.Web.Mvc.WebViewPage<CompraloTo.ViewModels.CustomerListViewModel>
    {
        public _Views_Customers_CustomerListView_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Customers\CustomerListView.cshtml"
  
    ViewBag.Title = "CustomerListView";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<a");

WriteLiteral(" class=\"btn btn-primary btn-sm\"");

WriteLiteral(" href=\"/customers/create\"");

WriteLiteral(">\r\n    Crear nuevo cliente <i");

WriteLiteral(" class=\"fa fa-plus\"");

WriteLiteral("></i>\r\n</a>\r\n\r\n");

            
            #line 11 "..\..\Views\Customers\CustomerListView.cshtml"
 using (Html.BeginForm("Index", "Customers", FormMethod.Get))
{
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Customers\CustomerListView.cshtml"
Write(Html.HiddenFor(m => m.sortField));

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Customers\CustomerListView.cshtml"
                                     
    
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Customers\CustomerListView.cshtml"
Write(Html.HiddenFor(m => m.sortDir));

            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Customers\CustomerListView.cshtml"
                                   

    
            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\Customers\CustomerListView.cshtml"
Write(Html.TextBoxFor(m => m.searchText, new { @class= "form-control" }));

            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\Customers\CustomerListView.cshtml"
                                                                       


            
            #line default
            #line hidden
WriteLiteral("    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Buscar\"");

WriteLiteral(" />\r\n");

            
            #line 19 "..\..\Views\Customers\CustomerListView.cshtml"

}

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<table");

WriteLiteral(" class=\"table table-bordered table-hover table-striped\"");

WriteLiteral(">\r\n\r\n    <thead>\r\n        <tr>\r\n            <th");

WriteLiteral(" style=\"width:200px;\"");

WriteLiteral("></th>\r\n            \r\n            <th>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 684), Tuple.Create("\"", 805)
, Tuple.Create(Tuple.Create("", 691), Tuple.Create("/customers?sortField=name", 691), true)
            
            #line 30 "..\..\Views\Customers\CustomerListView.cshtml"
, Tuple.Create(Tuple.Create("", 716), Tuple.Create<System.Object, System.Int32>(Model.sortField == "name" && Model.sortDir == "asc" ? "&sortDir=desc" : "&sortDir=asc"
            
            #line default
            #line hidden
, 716), false)
);

WriteLiteral(">\r\n                    Nombre\r\n\r\n");

            
            #line 33 "..\..\Views\Customers\CustomerListView.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\Customers\CustomerListView.cshtml"
                     if (Model.sortField == "name")
                    {
                        if (Model.sortDir == "asc")
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <i");

WriteLiteral(" class=\"fa fa-arrow-up\"");

WriteLiteral("></i>\r\n");

            
            #line 38 "..\..\Views\Customers\CustomerListView.cshtml"
                        }
                        else if (Model.sortDir == "desc")
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <i");

WriteLiteral(" class=\"fa fa-arrow-down\"");

WriteLiteral("></i>\r\n");

            
            #line 42 "..\..\Views\Customers\CustomerListView.cshtml"
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("                </a>\r\n            </th>\r\n            \r\n            <th>\r\n        " +
"        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1371), Tuple.Create("\"", 1525)
, Tuple.Create(Tuple.Create("", 1378), Tuple.Create("/customers?sortField=lastname", 1378), true)
            
            #line 48 "..\..\Views\Customers\CustomerListView.cshtml"
, Tuple.Create(Tuple.Create("", 1407), Tuple.Create<System.Object, System.Int32>(string.Compare(Model.sortField, "lastName", true) == 0 && Model.sortDir == "asc" ? "&sortDir=desc" : "&sortDir=asc"
            
            #line default
            #line hidden
, 1407), false)
);

WriteLiteral(">\r\n                Apellidos\r\n\r\n");

            
            #line 51 "..\..\Views\Customers\CustomerListView.cshtml"
                
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Customers\CustomerListView.cshtml"
                 if (string.Compare(Model.sortField, "lastName", true) == 0)
                {
                    if (Model.sortDir == "asc")
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <i");

WriteLiteral(" class=\"fa fa-arrow-up\"");

WriteLiteral("></i>\r\n");

            
            #line 56 "..\..\Views\Customers\CustomerListView.cshtml"
                    }
                    else if (Model.sortDir == "desc")
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <i");

WriteLiteral(" class=\"fa fa-arrow-down\"");

WriteLiteral("></i>\r\n");

            
            #line 60 "..\..\Views\Customers\CustomerListView.cshtml"
                    }
                }

            
            #line default
            #line hidden
WriteLiteral("                </a>\r\n            </th>\r\n\r\n            <th>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2063), Tuple.Create("\"", 2186)
, Tuple.Create(Tuple.Create("", 2070), Tuple.Create("/customers?sortField=phone", 2070), true)
            
            #line 66 "..\..\Views\Customers\CustomerListView.cshtml"
, Tuple.Create(Tuple.Create("", 2096), Tuple.Create<System.Object, System.Int32>(Model.sortField == "phone" && Model.sortDir == "asc" ? "&sortDir=desc" : "&sortDir=asc"
            
            #line default
            #line hidden
, 2096), false)
);

WriteLiteral(">\r\n                Teléfono\r\n\r\n");

            
            #line 69 "..\..\Views\Customers\CustomerListView.cshtml"
                
            
            #line default
            #line hidden
            
            #line 69 "..\..\Views\Customers\CustomerListView.cshtml"
                 if (Model.sortField == "phone")
                {
                    if (Model.sortDir == "asc")
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <i");

WriteLiteral(" class=\"fa fa-arrow-up\"");

WriteLiteral("></i>\r\n");

            
            #line 74 "..\..\Views\Customers\CustomerListView.cshtml"
                    }
                    else if (Model.sortDir == "desc")
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <i");

WriteLiteral(" class=\"fa fa-arrow-down\"");

WriteLiteral("></i>\r\n");

            
            #line 78 "..\..\Views\Customers\CustomerListView.cshtml"
                    }
                }            

            
            #line default
            #line hidden
WriteLiteral("                </a>\r\n            </th>\r\n            <th>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2705), Tuple.Create("\"", 2828)
, Tuple.Create(Tuple.Create("", 2712), Tuple.Create("/customers?sortField=email", 2712), true)
            
            #line 83 "..\..\Views\Customers\CustomerListView.cshtml"
, Tuple.Create(Tuple.Create("", 2738), Tuple.Create<System.Object, System.Int32>(Model.sortField == "email" && Model.sortDir == "asc" ? "&sortDir=desc" : "&sortDir=asc"
            
            #line default
            #line hidden
, 2738), false)
);

WriteLiteral(">\r\n                Email\r\n            \r\n");

            
            #line 86 "..\..\Views\Customers\CustomerListView.cshtml"
                
            
            #line default
            #line hidden
            
            #line 86 "..\..\Views\Customers\CustomerListView.cshtml"
                 if (Model.sortField == "email")
                {
                    if (Model.sortDir == "asc")
                    {

            
            #line default
            #line hidden
WriteLiteral("                    <i");

WriteLiteral(" class=\"fa fa-arrow-up\"");

WriteLiteral("></i>\r\n");

            
            #line 91 "..\..\Views\Customers\CustomerListView.cshtml"
                    }
                    else if (Model.sortDir == "desc")
                    {

            
            #line default
            #line hidden
WriteLiteral("                    <i");

WriteLiteral(" class=\"fa fa-arrow-down\"");

WriteLiteral("></i>\r\n");

            
            #line 95 "..\..\Views\Customers\CustomerListView.cshtml"
                    }
                }

            
            #line default
            #line hidden
WriteLiteral("                </a>\r\n            </th>\r\n        </tr>\r\n    </thead>\r\n\r\n\r\n    <tb" +
"ody>\r\n\r\n");

            
            #line 105 "..\..\Views\Customers\CustomerListView.cshtml"
        
            
            #line default
            #line hidden
            
            #line 105 "..\..\Views\Customers\CustomerListView.cshtml"
         foreach (var customer in Model.Customers)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n\r\n                <td>\r\n\r\n                    <a");

WriteLiteral(" class=\"btn btn-primary btn-xs\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3508), Tuple.Create("\"", 3543)
, Tuple.Create(Tuple.Create("", 3515), Tuple.Create("/customers/edit/", 3515), true)
            
            #line 111 "..\..\Views\Customers\CustomerListView.cshtml"
, Tuple.Create(Tuple.Create("", 3531), Tuple.Create<System.Object, System.Int32>(customer.ID
            
            #line default
            #line hidden
, 3531), false)
);

WriteLiteral(">\r\n                        Edit <i");

WriteLiteral(" class=\"fa fa-pencil\"");

WriteLiteral("></i>\r\n                    </a>\r\n\r\n                    &nbsp;\r\n");

WriteLiteral("                    ");

            
            #line 116 "..\..\Views\Customers\CustomerListView.cshtml"
               Write(Html.ActionLink("Eliminar", "Delete", new { id = customer.ID }, new { @class = "btn btn-xs btn-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                </td>\r\n\r\n                <td>");

            
            #line 120 "..\..\Views\Customers\CustomerListView.cshtml"
               Write(customer.name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 121 "..\..\Views\Customers\CustomerListView.cshtml"
               Write(customer.lastName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 122 "..\..\Views\Customers\CustomerListView.cshtml"
               Write(customer.phone);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 123 "..\..\Views\Customers\CustomerListView.cshtml"
               Write(customer.email);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\r\n            </tr>\r\n");

            
            #line 126 "..\..\Views\Customers\CustomerListView.cshtml"

        }

            
            #line default
            #line hidden
WriteLiteral("\r\n    </tbody>\r\n\r\n\r\n</table>\r\n");

        }
    }
}
#pragma warning restore 1591
