#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CompraloTo;
    using CompraloTo.Res;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Products/Create.cshtml")]
    public partial class _Views_Products_Create_cshtml : System.Web.Mvc.WebViewPage<CompraloTo.ViewModels.CreateUpdateProductViewModel>
    {

#line 7 "..\..\Views\Products\Create.cshtml"
public System.Web.WebPages.HelperResult PrintTitle(string title)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 8 "..\..\Views\Products\Create.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <h4>");


#line 9 "..\..\Views\Products\Create.cshtml"
WriteTo(__razor_helper_writer, title);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</h4>\r\n");

WriteLiteralTo(__razor_helper_writer, "    <hr />\r\n");


#line 11 "..\..\Views\Products\Create.cshtml"


#line default
#line hidden
});

#line 11 "..\..\Views\Products\Create.cshtml"
}
#line default
#line hidden

        public _Views_Products_Create_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Products\Create.cshtml"
  
    ViewBag.Title = "Create";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n\r\n\r\n");

            
            #line 15 "..\..\Views\Products\Create.cshtml"
 if (Model != null && !string.IsNullOrEmpty(Model.errorMessage))
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"alert alert-danger\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 18 "..\..\Views\Products\Create.cshtml"
   Write(Model.errorMessage);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 20 "..\..\Views\Products\Create.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 23 "..\..\Views\Products\Create.cshtml"
 using (Html.BeginForm()) 
{
    
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\Products\Create.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\Products\Create.cshtml"
                            


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("        ");

            
            #line 29 "..\..\Views\Products\Create.cshtml"
   Write(PrintTitle("Crear producto"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("        ");

            
            #line 31 "..\..\Views\Products\Create.cshtml"
   Write(Html.ValidationSummary(true, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 35 "..\..\Views\Products\Create.cshtml"
       Write(Html.LabelFor(model => model.product.name, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 37 "..\..\Views\Products\Create.cshtml"
           Write(Html.TextBoxFor(model => model.product.name, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 38 "..\..\Views\Products\Create.cshtml"
           Write(Html.ValidationMessageFor(model => model.product.name, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 43 "..\..\Views\Products\Create.cshtml"
       Write(Html.LabelFor(model => model.product.price, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 45 "..\..\Views\Products\Create.cshtml"
           Write(Html.TextBoxFor(model => model.product.price, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 46 "..\..\Views\Products\Create.cshtml"
           Write(Html.ValidationMessageFor(model => model.product.price, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n\r\n\r\n        <hr/>\r\n\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 54 "..\..\Views\Products\Create.cshtml"
       Write(Html.LabelFor(model => model.product.categoryID, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 56 "..\..\Views\Products\Create.cshtml"
           Write(Html.DropDownListFor(model => model.product.categoryID, Model.categories, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 57 "..\..\Views\Products\Create.cshtml"
           Write(Html.ValidationMessageFor(model => model.product.categoryID, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n\r\n\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-offset-2 col-md-10\"");

WriteLiteral(">\r\n                <label>\r\n");

WriteLiteral("                    ");

            
            #line 65 "..\..\Views\Products\Create.cshtml"
               Write(Html.CheckBoxFor(model => model.product.hightlighted));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 66 "..\..\Views\Products\Create.cshtml"
               Write(Html.DisplayNameFor(model => model.product.hightlighted));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </label>\r\n            </div>\r\n        </div>\r\n\r\n        <hr />\r" +
"\n\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 74 "..\..\Views\Products\Create.cshtml"
       Write(Html.LabelFor(model => model.product.description, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 76 "..\..\Views\Products\Create.cshtml"
           Write(Html.TextAreaFor(model => model.product.description, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 77 "..\..\Views\Products\Create.cshtml"
           Write(Html.ValidationMessageFor(model => model.product.description, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n\r\n        <hr />\r\n\r\n");

WriteLiteral("        ");

            
            #line 83 "..\..\Views\Products\Create.cshtml"
   Write(Html.DropZone( m=> m.fileServer, "/products/upload"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-offset-2 col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 88 "..\..\Views\Products\Create.cshtml"
           Write(Html.Submit("Crear"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 92 "..\..\Views\Products\Create.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<div>\r\n");

WriteLiteral("    ");

            
            #line 95 "..\..\Views\Products\Create.cshtml"
Write(Html.ActionLink("Back to List", nameof(CompraloTo.Controllers.ProductsController.ProductsView)));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
