#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CompraloTo;
    using CompraloTo.Res;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Products/ProductsView.cshtml")]
    public partial class _Views_Products_ProductsView_cshtml : System.Web.Mvc.WebViewPage<CompraloTo.ViewModels.ProductListViewModel>
    {
        public _Views_Products_ProductsView_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Products\ProductsView.cshtml"
  
    ViewBag.Title = "Products";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<p>\r\n");

WriteLiteral("    ");

            
            #line 10 "..\..\Views\Products\ProductsView.cshtml"
Write(Html.ActionLink("Nuevo producto", nameof(CompraloTo.Controllers.ProductsController.Create), "Products"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n\r\n\r\n\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n\r\n\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 24 "..\..\Views\Products\ProductsView.cshtml"
               Write(Html.LabelFor(model => model.categoryID, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 26 "..\..\Views\Products\ProductsView.cshtml"
                   Write(Html.DropDownListFor(model => model.categoryID, Model.categories,
                            "Todas las categorías", new { @class = "form-control", id = "categories-dropdown" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n            </div>\r\n\r\n\r\n " +
"       </div>\r\n    </div>\r\n\r\n\r\n    <div");

WriteLiteral(" id=\"products-container\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 39 "..\..\Views\Products\ProductsView.cshtml"
   Write(Html.Partial("ProductsListView"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n\r\n</div>\r\n\r\n\r\n");

DefineSection("PageScripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\r\n        //when categories change\r\n        $(\'#categories-dropdown\').change(f" +
"unction () {\r\n\r\n            $.ajax({\r\n                url: \'/products/list\',\r\n  " +
"              contentType: \'application/html; charset=utf-8\',\r\n                t" +
"ype: \'GET\',\r\n                data: { categoryID: this.value },\r\n                " +
"dataType: \'html\'\r\n            })\r\n            .success(function (result) {\r\n    " +
"            $(\'#products-container\').html(result);\r\n            })\r\n            " +
".error(function (xhr, status) {\r\n                alert(status);\r\n            });" +
"\r\n\r\n        });\r\n\r\n\r\n        //when user clicks on add/remove to/from shopping c" +
"art\r\n        $(\'#products-container\').on(\'click\', \'div.btn\', function () {\r\n\r\n  " +
"          var $this = $(this);\r\n            var productID = $this.siblings(\"inpu" +
"t[name=product-id]\").val();\r\n            var addField = $this.siblings(\"input[na" +
"me=add-to-cart]\");\r\n            var add = addField.val() == 1;\r\n\r\n            $t" +
"his.children(\'i\').removeClass(\'fa-plus fa-minus\').addClass(\'fa-refresh fa-spin\')" +
";\r\n\r\n            $.ajax({\r\n                url: add ? \'/cart/add\' : \'/cart/remov" +
"e\',\r\n                type: \'POST\',\r\n                data: { productID: productID" +
" },\r\n            })\r\n            .success(function (result) {\r\n                \r" +
"\n                //update hidden field value\r\n                addField.val(add ?" +
" \'0\' : \'1\');\r\n\r\n                //set button text\r\n                $this.childre" +
"n(\'span\').html(add ? \'Eliminar de la cesta\' : \'Añadir a la cesta\');\r\n\r\n\r\n       " +
"         $this.children(\'i\').removeClass(\'fa-refresh fa-spin\');\r\n               " +
" if (add) {\r\n                    $this.children(\'i\').removeClass(\'fa-plus\').addC" +
"lass(\'fa-minus\');\r\n                } else {\r\n                    $this.children(" +
"\'i\').removeClass(\'fa-minus\').addClass(\'fa-plus\');\r\n                }\r\n\r\n        " +
"        //update shopping cart count\r\n                $(\'#cart-count\').html(resu" +
"lt);\r\n\r\n            })\r\n            .error(function (xhr, status) {\r\n\r\n         " +
"       $this.children(\'i\').removeClass(\'fa-refresh fa-spin\');\r\n\r\n               " +
" alert(status);\r\n            });\r\n\r\n        });\r\n\r\n\r\n    </script>\r\n\r\n");

});

        }
    }
}
#pragma warning restore 1591
