#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CompraloTo;
    using CompraloTo.Res;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Products/ProductsListView.cshtml")]
    public partial class _Views_Products_ProductsListView_cshtml : System.Web.Mvc.WebViewPage<CompraloTo.ViewModels.ProductListViewModel>
    {
        public _Views_Products_ProductsListView_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Products\ProductsListView.cshtml"
  

    int columns = 4;
    int column = 1;


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n");

            
            #line 12 "..\..\Views\Products\ProductsListView.cshtml"
 for (int i = 0; i < Model.products.Count; i++)
{
    var product = Model.products[i];

    if(column == 1)
    {
        
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Products\ProductsListView.cshtml"
   Write(Html.Raw("<div class=\"row\">"));

            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Products\ProductsListView.cshtml"
                                        
    }

    
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Products\ProductsListView.cshtml"
                                 

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 396), Tuple.Create("\"", 432)
, Tuple.Create(Tuple.Create("", 403), Tuple.Create("/products/details/", 403), true)
            
            #line 24 "..\..\Views\Products\ProductsListView.cshtml"
, Tuple.Create(Tuple.Create("", 421), Tuple.Create<System.Object, System.Int32>(product.ID
            
            #line default
            #line hidden
, 421), false)
);

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"thumbnail\"");

WriteLiteral(">\r\n\r\n                <div");

WriteLiteral(" class=\"bg-info clearfix\"");

WriteLiteral(">\r\n");

            
            #line 28 "..\..\Views\Products\ProductsListView.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Products\ProductsListView.cshtml"
                     if (product.hightlighted)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <i");

WriteLiteral(" class=\"fa fa-lg fa-star\"");

WriteLiteral("></i>\r\n");

            
            #line 31 "..\..\Views\Products\ProductsListView.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <span>");

            
            #line 32 "..\..\Views\Products\ProductsListView.cshtml"
                     Write(product.name);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </div>\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 767), Tuple.Create("\"", 812)
, Tuple.Create(Tuple.Create("", 773), Tuple.Create<System.Object, System.Int32>(Href("~/public/img/products/")
, 773), false)
            
            #line 34 "..\..\Views\Products\ProductsListView.cshtml"
, Tuple.Create(Tuple.Create("", 795), Tuple.Create<System.Object, System.Int32>(product.ID
            
            #line default
            #line hidden
, 795), false)
, Tuple.Create(Tuple.Create("", 808), Tuple.Create(".jpg", 808), true)
);

WriteLiteral(" style=\"max-height:100px;\"");

WriteLiteral(" />\r\n            </div>\r\n            <h6>");

            
            #line 36 "..\..\Views\Products\ProductsListView.cshtml"
           Write(product.price.ToString("c"));

            
            #line default
            #line hidden
WriteLiteral("</h6>\r\n        </a>\r\n\r\n        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"add-to-cart\"");

WriteLiteral(" value=\"1\"");

WriteLiteral(" />\r\n        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"product-id\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1039), Tuple.Create("\"", 1058)
            
            #line 40 "..\..\Views\Products\ProductsListView.cshtml"
, Tuple.Create(Tuple.Create("", 1047), Tuple.Create<System.Object, System.Int32>(product.ID
            
            #line default
            #line hidden
, 1047), false)
);

WriteLiteral(" />\r\n        \r\n        <div");

WriteLiteral(" class=\"btn btn-sm btn-primary btn-block\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"fa fa-plus\"");

WriteLiteral("></i>\r\n            <span>Añadir a la cesta</span>\r\n        </div>\r\n\r\n    </div>\r\n" +
"");

            
            #line 48 "..\..\Views\Products\ProductsListView.cshtml"


    if (column == columns || i == Model.products.Count - 1)
    {
        
            
            #line default
            #line hidden
            
            #line 52 "..\..\Views\Products\ProductsListView.cshtml"
                      
        
            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\Products\ProductsListView.cshtml"
   Write(Html.Raw("</div>"));

            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\Products\ProductsListView.cshtml"
                           

        
            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\Products\ProductsListView.cshtml"
                          
        column = 0;
    }

    column++;


}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
