#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CompraloTo;
    using CompraloTo.Res;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n\r\n<head>\r\n\r\n");

WriteLiteral("    ");

            
            #line 6 "..\..\Views\Shared\_Layout.cshtml"
Write(Html.Partial("HeadView"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <link");

WriteLiteral(" rel=\"Shortcut Icon\"");

WriteAttribute("href", Tuple.Create(" href=\"", 99), Tuple.Create("\"", 126)
, Tuple.Create(Tuple.Create("", 106), Tuple.Create<System.Object, System.Int32>(Href("~/public/favicon.ico")
, 106), false)
);

WriteLiteral(" />\r\n\r\n</head>\r\n\r\n<body>\r\n\r\n    ");

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 15 "..\..\Views\Shared\_Layout.cshtml"
Write(Html.Partial("NavHeaderView"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n    ");

WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"container body-content\"");

WriteLiteral(">\r\n\r\n\r\n");

WriteLiteral("        ");

            
            #line 22 "..\..\Views\Shared\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n        <hr />\r\n        <footer>\r\n            <p>&copy; ");

            
            #line 27 "..\..\Views\Shared\_Layout.cshtml"
                 Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral(" - LosMegaCursos.com - CompraloTó</p>\r\n        </footer>\r\n\r\n    </div>\r\n\r\n\r\n    ");

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 34 "..\..\Views\Shared\_Layout.cshtml"
Write(Html.Partial("Scripts"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n    ");

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 38 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("PageScripts", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n    \r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
