#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CompraloTo;
    using CompraloTo.Res;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/NavHeaderView.cshtml")]
    public partial class _Views_Shared_NavHeaderView_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_NavHeaderView_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"navbar navbar-default\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"navbar-toggle\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\".navbar-collapse\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n            </button>\r\n");

WriteLiteral("            ");

            
            #line 11 "..\..\Views\Shared\NavHeaderView.cshtml"
       Write(Html.ActionLink("CompraloTó", "Index", "Home", null, new { @class = "navbar-brand" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n\r\n        <div");

WriteLiteral(" class=\"navbar-collapse collapse\"");

WriteLiteral(">\r\n\r\n            <ul");

WriteLiteral(" class=\"nav navbar-nav\"");

WriteLiteral(">\r\n                <li>");

            
            #line 18 "..\..\Views\Shared\NavHeaderView.cshtml"
               Write(Html.ActionLink("Catálogo", nameof(CompraloTo.Controllers.ProductsController.ProductsView), "Products"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                <li>\r\n                    <a>\r\n                        <i");

WriteLiteral(" class=\"fa fa-shopping-cart\"");

WriteLiteral("></i>\r\n                        <span");

WriteLiteral(" id=\"cart-count\"");

WriteLiteral(" class=\"badge\"");

WriteLiteral(">0</span>\r\n                    </a>\r\n                </li>\r\n            </ul>\r\n\r\n" +
"            <ul");

WriteLiteral(" class=\"nav navbar-nav navbar-right\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("                ");

            
            #line 29 "..\..\Views\Shared\NavHeaderView.cshtml"
           Write(Html.Action("LanguagesDropdown", "Home"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                <li>");

            
            #line 31 "..\..\Views\Shared\NavHeaderView.cshtml"
               Write(Html.ActionLink("Registro", nameof(CompraloTo.Controllers.AccountController.Register), "Account"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n            </ul>\r\n\r\n        </div>\r\n        \r\n    </div>\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
