#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CompraloTo;
    using CompraloTo.Res;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Scripts.cshtml")]
    public partial class _Views_Shared_Scripts_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Scripts_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

            
            #line 3 "..\..\Views\Shared\Scripts.cshtml"
 if (Utils.InProduction)
{
    
            
            #line default
            #line hidden
            
            #line 5 "..\..\Views\Shared\Scripts.cshtml"
                         

            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 71), Tuple.Create("\"", 127)
, Tuple.Create(Tuple.Create("", 77), Tuple.Create<System.Object, System.Int32>(Href("~/public/js/libs.min.js?ver=")
, 77), false)
            
            #line 6 "..\..\Views\Shared\Scripts.cshtml"
, Tuple.Create(Tuple.Create("", 105), Tuple.Create<System.Object, System.Int32>(Utils.AssemblyVersion
            
            #line default
            #line hidden
, 105), false)
);

WriteLiteral("></script>\r\n");

            
            #line 7 "..\..\Views\Shared\Scripts.cshtml"
}
else
{

    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Shared\Scripts.cshtml"
                           

    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Shared\Scripts.cshtml"
               

            
            #line default
            #line hidden
WriteLiteral("    <!-- bower:js -->\r\n");

WriteLiteral("    <script");

WriteLiteral(" src=\"/public/js/libs/jquery/dist/jquery.js\"");

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteLiteral(" src=\"/public/js/libs/dropzone/dist/min/dropzone.min.js\"");

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteLiteral(" src=\"/public/js/libs/jquery-validation/dist/jquery.validate.js\"");

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteLiteral(" src=\"/public/js/libs/jquery-validation-unobtrusive/jquery.validate.unobtrusive.j" +
"s\"");

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteLiteral(" src=\"/public/js/libs/bootstrap/dist/js/bootstrap.js\"");

WriteLiteral("></script>\r\n");

WriteLiteral("    <!-- endbower -->\r\n");

            
            #line 21 "..\..\Views\Shared\Scripts.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
