#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CompraloTo;
    using CompraloTo.Res;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Error/_LayoutError.cshtml")]
    public partial class _Views_Error__LayoutError_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Error__LayoutError_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n\r\n    <link");

WriteLiteral(" rel=\"Shortcut Icon\"");

WriteAttribute("href", Tuple.Create(" href=\"", 64), Tuple.Create("\"", 91)
, Tuple.Create(Tuple.Create("", 71), Tuple.Create<System.Object, System.Int32>(Href("~/public/favicon.ico")
, 71), false)
);

WriteLiteral(" />\r\n\r\n</head>\r\n\r\n<body>\r\n\r\n");

WriteLiteral("    ");

            
            #line 11 "..\..\Views\Error\_LayoutError.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    \r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
